<?php

return [
    ['price' => '500', 'locales' => ['hy' => 'Երևան', 'ru' => 'Ереван', 'en' => 'Yerevan']],
    ['price' => '1400', 'locales' => ['hy' => 'Աբովյան', 'ru' => 'Абовян', 'en' => 'Abovyan']],
    ['price' => '9200', 'locales' => ['hy' => 'Ազատան', 'ru' => 'Азатан', 'en' => 'Azatan']],
    ['price' => '2400', 'locales' => ['hy' => 'Ազատավան', 'ru' => 'Азатаван', 'en' => 'Azatavan']],
    ['price' => '15400', 'locales' => ['hy' => 'Ալավերդի', 'ru' => 'Алаверди', 'en' => 'Alaverdi']],
    ['price' => '10200', 'locales' => ['hy' => 'Ախուրյան', 'ru' => 'Ахурян', 'en' => 'Akhuryan']],
    ['price' => '4000', 'locales' => ['hy' => 'Աղվերան', 'ru' => 'Агверан', 'en' => 'Aghveran']],
    ['price' => '11900', 'locales' => ['hy' => 'Ամասիա', 'ru' => 'Амасия', 'en' => 'Amasia']],
    ['price' => '13300', 'locales' => ['hy' => 'Աշոցք', 'ru' => 'Ашоцк', 'en' => 'Ashotsk']],
    ['price' => '1900', 'locales' => ['hy' => 'Աշտարակ', 'ru' => 'Аштарак', 'en' => 'Ashtarak']],
    ['price' => '4800', 'locales' => ['hy' => 'Ապարան', 'ru' => 'Апаран', 'en' => 'Aparan']],
    ['price' => '4200', 'locales' => ['hy' => 'Ավշար', 'ru' => 'Авшар', 'en' => 'Avshar']],
    ['price' => '3700', 'locales' => ['hy' => 'Արագած', 'ru' => 'Арагац', 'en' => 'Aragats']],
    ['price' => '3700', 'locales' => ['hy' => 'Արալեզ', 'ru' => 'Аралез', 'en' => 'Aralez']],
    ['price' => '1600', 'locales' => ['hy' => 'Արամուս', 'ru' => 'Арамус', 'en' => 'Aramus']],
    ['price' => '5500', 'locales' => ['hy' => 'Արարատ', 'ru' => 'Арарат', 'en' => 'Ararat']],
    ['price' => '9000', 'locales' => ['hy' => 'Արենի', 'ru' => 'Арени', 'en' => 'Areni']],
    ['price' => '3400', 'locales' => ['hy' => 'Արզական', 'ru' => 'Арзакан', 'en' => 'Arzakan']],
    ['price' => '1600', 'locales' => ['hy' => 'Արզնի', 'ru' => 'Арзни', 'en' => 'Arzni']],
    ['price' => '8500', 'locales' => ['hy' => 'Արթիկ', 'ru' => 'Артик', 'en' => 'Artik']],
    ['price' => '3900', 'locales' => ['hy' => 'Արմավիր', 'ru' => 'Армавир', 'en' => 'Armavir']],
    ['price' => '2600', 'locales' => ['hy' => 'Արտաշատ', 'ru' => 'Арташат', 'en' => 'Artashat']],
    ['price' => '17000 ', 'locales' => ['hy' => 'Բերդ', 'ru' => 'Берд', 'en' => 'Berd']],
    ['price' => '3000', 'locales' => ['hy' => 'Բյուրական', 'ru' => 'Бюракан', 'en' => 'Byurakan']],
    ['price' => '1800', 'locales' => ['hy' => 'Բյուրեղավան', 'ru' => 'Бюрегаван', 'en' => 'Byureghavan']],
    ['price' => '3600', 'locales' => ['hy' => 'Բջնի', 'ru' => 'Бжни', 'en' => 'Bjni']],
    ['price' => '2300', 'locales' => ['hy' => 'Գառնի', 'ru' => 'Гарни', 'en' => 'Garni']],
    ['price' => '7900', 'locales' => ['hy' => 'Գավառ', 'ru' => 'Гавар', 'en' => 'Gavar']],
    ['price' => '2600', 'locales' => ['hy' => 'Գեղարդ', 'ru' => 'Гегард', 'en' => 'Geghard']],
    ['price' => '10200', 'locales' => ['hy' => 'Գյումրի', 'ru' => 'Гюмри', 'en' => 'Gyumri']],
    ['price' => '20000', 'locales' => ['hy' => 'Գորիս', 'ru' => 'Горис', 'en' => 'Goris']],
    ['price' => '8000', 'locales' => ['hy' => 'Դիլիջան', 'ru' => 'Дилижан', 'en' => 'Dilijan']],
    ['price' => '9900', 'locales' => ['hy' => 'Եղեգնաձոր', 'ru' => 'Ехегнадзор', 'en' => 'Yeghegnadzor']],
    ['price' => '1600', 'locales' => ['hy' => 'Եղվարդ', 'ru' => 'Егвард', 'en' => 'Yeghvard']],
    ['price' => '1400', 'locales' => ['hy' => 'Զվարթնոց', 'ru' => 'Звартноц', 'en' => 'Zvartnots']],
    ['price' => '1600', 'locales' => ['hy' => 'Էջմիածին', 'ru' => 'Эчмиадзин', 'en' => 'Echmiadzin']],
    ['price' => '6000', 'locales' => ['hy' => 'Թալին', 'ru' => 'Талин', 'en' => 'Talin']],
    ['price' => '11500', 'locales' => ['hy' => 'Իջևան', 'ru' => 'Иджеван', 'en' => 'Ijevan']],
    ['price' => '2100', 'locales' => ['hy' => 'Լուսակերտ', 'ru' => 'Лусакерт', 'en' => 'Lusakert']],
    ['price' => '19900', 'locales' => ['hy' => 'Խնձորեսկ', 'ru' => 'Хндзореск', 'en' => 'Khndzoresk']],
    ['price' => '6400', 'locales' => ['hy' => 'Ծաղկաձոր', 'ru' => 'Цахкадзор', 'en' => 'Tsaghkadzor']],
    ['price' => '5200', 'locales' => ['hy' => 'Կաթնաղբյուր, Արագածոտն', 'ru' => 'Катнахпюр, Арагацотн', 'en' => 'Katnaghbyur, Aragatsotn']],
    ['price' => '1800', 'locales' => ['hy' => 'Կաթնաղբյուր, Կոտայք', 'ru' => 'Катнахпюр, Котайк', 'en' => 'Katnaghbyur, Kotayk']],
    ['price' => '25600', 'locales' => ['hy' => 'Կապան', 'ru' => 'Капан', 'en' => 'Kapan']],
    ['price' => '3500', 'locales' => ['hy' => 'Կոշ', 'ru' => 'Кош', 'en' => 'Kosh']],
    ['price' => '6600', 'locales' => ['hy' => 'Հանքավան', 'ru' => 'Анкаван', 'en' => 'Hankavan']],
    ['price' => '4000', 'locales' => ['hy' => 'Հրազդան', 'ru' => 'Раздан', 'en' => 'Hrazdan']],
    ['price' => '1400', 'locales' => ['hy' => 'Ձորաղբյուր', 'ru' => 'Дзорахпюр', 'en' => 'Dzoraghbyur']],
    ['price' => '10100', 'locales' => ['hy' => 'Ճամբարակ', 'ru' => 'Чамбарак', 'en' => 'Chambarak']],
    ['price' => '1600', 'locales' => ['hy' => 'Մասիս', 'ru' => 'Масис', 'en' => 'Masis']],
    ['price' => '8500', 'locales' => ['hy' => 'Մարալիկ', 'ru' => 'Маралик', 'en' => 'Maralik']],
    ['price' => '10400', 'locales' => ['hy' => 'Մարտունի', 'ru' => 'Мартуни', 'en' => 'Martuni']],
    ['price' => '5300', 'locales' => ['hy' => 'Մելիքգյուղ, Արագածոտն', 'ru' => 'Меликгюх, Арагацотн', 'en' => 'Melikgyugh, Aragatsotn']],
    ['price' => '3100', 'locales' => ['hy' => 'Մեծամոր', 'ru' => 'Мецамор', 'en' => 'Metsamor']],
    ['price' => '5500', 'locales' => ['hy' => 'Մեղրաձոր', 'ru' => 'Меградзор', 'en' => 'Meghradzor']],
    ['price' => '31600', 'locales' => ['hy' => 'Մեղրի', 'ru' => 'Мегри', 'en' => 'Meghri']],
    ['price' => '12000', 'locales' => ['hy' => 'Մեղրուտ', 'ru' => 'Мегрут', 'en' => 'Meghrut']],
    ['price' => '2000', 'locales' => ['hy' => 'Մուղնի, Աշտարակ', 'ru' => 'Мугни, Аштарак', 'en' => 'Mughni, Ashtarak']],
    ['price' => '15400', 'locales' => ['hy' => 'Նոյեմբերյան', 'ru' => 'Ноемберян', 'en' => 'Noyemberyan']],
    ['price' => '1900', 'locales' => ['hy' => 'Նոր Գեղի', 'ru' => 'Нор Геги', 'en' => 'Nor Geghi']],
    ['price' => '1600', 'locales' => ['hy' => 'Նոր Հաճն', 'ru' => 'Нор Ачн', 'en' => 'Nor Hachn']],
    ['price' => '1300', 'locales' => ['hy' => 'Նուբարաշեն', 'ru' => 'Нубарашен', 'en' => 'Nubarashen']],
    ['price' => '9400', 'locales' => ['hy' => 'Շիրակավան', 'ru' => 'Ширакаван', 'en' => 'Shirakavan']],
    ['price' => '3000', 'locales' => ['hy' => 'Ուջան', 'ru' => 'Уджан', 'en' => 'Ujan']],
    ['price' => '2900', 'locales' => ['hy' => 'Չարենցավան', 'ru' => 'Чаренцаван', 'en' => 'Charentsavan']],
    ['price' => '2400', 'locales' => ['hy' => 'Փարպի, Արագածոտն', 'ru' => 'Парпи, Арагацотн', 'en' => 'Parpi, Aragatsotn']],
    ['price' => '1300', 'locales' => ['hy' => 'Պռոշյան (գյուղ)', 'ru' => 'Прошян (село)', 'en' => 'Proshyan (village)']],
    ['price' => '1100', 'locales' => ['hy' => 'Պտղնի', 'ru' => 'Птхни', 'en' => 'Ptghni']],
    ['price' => '14300', 'locales' => ['hy' => 'Ջերմուկ', 'ru' => 'Джермук', 'en' => 'Jermuk']],
    ['price' => '7100', 'locales' => ['hy' => 'Ջրաշեն', 'ru' => 'Джрашен', 'en' => 'Jrashen']],
    ['price' => '5400', 'locales' => ['hy' => 'Սևան', 'ru' => 'Севан', 'en' => 'Sevan']],
    ['price' => '17400', 'locales' => ['hy' => 'Սիսիան', 'ru' => 'Сисиан', 'en' => 'Sisian']],
    ['price' => '8200', 'locales' => ['hy' => 'Սպիտակ', 'ru' => 'Спитак', 'en' => 'Spitak']],
    ['price' => '12600', 'locales' => ['hy' => 'Ստեփանավան', 'ru' => 'Степанаван', 'en' => 'Stepanavan']],
    ['price' => '11200', 'locales' => ['hy' => 'Վայք', 'ru' => 'Вайк', 'en' => 'Vayk']],
    ['price' => '10100', 'locales' => ['hy' => 'Վանաձոր', 'ru' => 'Ванадзор', 'en' => 'Vanadzor']],
    ['price' => '13500', 'locales' => ['hy' => 'Վարդենիս', 'ru' => 'Варденис', 'en' => 'Vardenis']],
    ['price' => '4000', 'locales' => ['hy' => 'Վեդի', 'ru' => 'Веди', 'en' => 'Vedi']],
    ['price' => '14000', 'locales' => ['hy' => 'Տաշիր', 'ru' => 'Ташир', 'en' => 'Tashir']],
    ['price' => '26200', 'locales' => ['hy' => 'Քաջարան', 'ru' => 'Каджаран', 'en' => 'Kajaran']],
    ['price' => '2300', 'locales' => ['hy' => 'Օշական', 'ru' => 'Ошакан', 'en' => 'Oshakan']],
    ['price' => '29600', 'locales' => ['hy' => 'Ասկերան', 'ru' => 'Аскеран', 'en' => 'Askeran']],
    ['price' => '35200', 'locales' => ['hy' => 'Հադրութ', 'ru' => 'Гадрут', 'en' => 'Hadrut']],
    ['price' => '32800', 'locales' => ['hy' => 'Մարտակերտ', 'ru' => 'Мартакерт', 'en' => 'Martakert']],
    ['price' => '24800', 'locales' => ['hy' => 'Շուշի', 'ru' => 'Шуши', 'en' => 'Shushi']],
    ['price' => '26400', 'locales' => ['hy' => 'Ստեփանակերտ', 'ru' => 'Степанакерт', 'en' => 'Stepanakert']],
    ['price' => '20300', 'locales' => ['hy' => 'Քարվաճառ', 'ru' => 'Карвачар', 'en' => 'Karvachar']],
    ['price' => '1000', 'locales' => ['hy' => 'Զովունի', 'ru' => 'Зовуни', 'en' => 'Zovuni']],
    ['price' => '1400', 'locales' => ['hy' => 'Մերձավան', 'ru' => 'Мердзаван', 'en' => 'Merdzavan']],
    ['price' => '1400', 'locales' => ['hy' => 'Գեղանիստ', 'ru' => 'Геганист', 'en' => 'Geghanist']],
];


