<?php

return [
    ['label' => 'Yerevan', 'price' => '0'],
    ['label' => 'Abovyan', 'price' => '1400'],
    ['label' => 'Azatan', 'price' => '9200'],
    ['label' => 'Azatavan', 'price' => '2400'],
    ['label' => 'Alaverdi', 'price' => '15400'],
    ['label' => 'Akhuryan', 'price' => '10200'],
    ['label' => 'Aghveran', 'price' => '4000'],
    ['label' => 'Amasia', 'price' => '11900'],
    ['label' => 'Ashotsk', 'price' => '13300'],
    ['label' => 'Ashtarak', 'price' => '1900'],
    ['label' => 'Aparan', 'price' => '4800'],
    ['label' => 'Avshar', 'price' => '4200'],
    ['label' => 'Aragats', 'price' => '3700'],
    ['label' => 'Aralez', 'price' => '3700'],
    ['label' => 'Aramus', 'price' => '1600'],
    ['label' => 'Ararat', 'price' => '5500'],
    ['label' => 'Areni', 'price' => '9000'],
    ['label' => 'Arzakan', 'price' => '3400'],
    ['label' => 'Arzni', 'price' => '1600'],
    ['label' => 'Artik', 'price' => '8500'],
    ['label' => 'Armavir', 'price' => '3900'],
    ['label' => 'Artashat', 'price' => '2600'],
    ['label' => 'Berd', 'price' => '17000 '],
    ['label' => 'Byurakan', 'price' => '3000'],
    ['label' => 'Byureghavan', 'price' => '1800'],
    ['label' => 'Bjni', 'price' => '3600'],
    ['label' => 'Garni', 'price' => '2300'],
    ['label' => 'Gavar', 'price' => '7900'],
    ['label' => 'Geghard', 'price' => '2600'],
    ['label' => 'Gyumri', 'price' => '10200'],
    ['label' => 'Goris', 'price' => '20000'],
    ['label' => 'Dilijan', 'price' => '8000'],
    ['label' => 'Yeghegnadzor', 'price' => '9900'],
    ['label' => 'Yeghvard', 'price' => '1600'],
    ['label' => 'Zvartnots', 'price' => '1400'],
    ['label' => 'Echmiadzin', 'price' => '1600'],
    ['label' => 'Talin', 'price' => '6000'],
    ['label' => 'Ijevan', 'price' => '11500'],
    ['label' => 'Lusakert', 'price' => '2100'],
    ['label' => 'Khndzoresk', 'price' => '19900'],
    ['label' => 'Tsaghkadzor', 'price' => '6400'],
    ['label' => 'Katnaghbyur, Aragatsotn', 'price' => '5200'],
    ['label' => 'Katnaghbyur, Kotayk', 'price' => '1800'],
    ['label' => 'Kapan', 'price' => '25600'],
    ['label' => 'Kosh', 'price' => '3500'],
    ['label' => 'Hankavan', 'price' => '6600'],
    ['label' => 'Hrazdan', 'price' => '4000'],
    ['label' => 'Dzoraghbyur', 'price' => '1400'],
    ['label' => 'Chambarak', 'price' => '10100'],
    ['label' => 'Masis', 'price' => '1600'],
    ['label' => 'Maralik', 'price' => '8500'],
    ['label' => 'Martuni', 'price' => '10400'],
    ['label' => 'Melikgyugh, Aragatsotn', 'price' => '5300'],
    ['label' => 'Metsamor', 'price' => '3100'],
    ['label' => 'Meghradzor', 'price' => '5500'],
    ['label' => 'Meghri', 'price' => '31600'],
    ['label' => 'Meghrut', 'price' => '12000'],
    ['label' => 'Mughni, Ashtarak', 'price' => '2000'],
    ['label' => 'Noyemberyan', 'price' => '15400'],
    ['label' => 'Nor Geghi', 'price' => '1900'],
    ['label' => 'Nor Hachn', 'price' => '1600'],
    ['label' => 'Nubarashen', 'price' => '1300'],
    ['label' => 'Shirakavan', 'price' => '9400'],
    ['label' => 'Ujan', 'price' => '3000'],
    ['label' => 'Charentsavan', 'price' => '2900'],
    ['label' => 'Parpi, Aragatsotn', 'price' => '2400'],
    ['label' => 'Proshyan (village)', 'price' => '1300'],
    ['label' => 'Ptghni', 'price' => '1100'],
    ['label' => 'Jermuk', 'price' => '14300'],
    ['label' => 'Jrashen', 'price' => '7100'],
    ['label' => 'Sevan', 'price' => '5400'],
    ['label' => 'Sisian', 'price' => '17400'],
    ['label' => 'Spitak', 'price' => '8200'],
    ['label' => 'Stepanavan', 'price' => '12600'],
    ['label' => 'Vayk', 'price' => '11200'],
    ['label' => 'Vanadzor', 'price' => '10100'],
    ['label' => 'Vardenis', 'price' => '13500'],
    ['label' => 'Vedi', 'price' => '4000'],
    ['label' => 'Tashir', 'price' => '14000'],
    ['label' => 'Kajaran', 'price' => '26200'],
    ['label' => 'Oshakan', 'price' => '2300'],
    ['label' => 'Askeran', 'price' => '29600'],
    ['label' => 'Hadrut', 'price' => '35200'],
    ['label' => 'Martakert', 'price' => '32800'],
    ['label' => 'Shushi', 'price' => '24800'],
    ['label' => 'Stepanakert', 'price' => '26400'],
    ['label' => 'Karvachar', 'price' => '20300'],
    ['label' => 'Zovuni', 'price' => '1000'],
    ['label' => 'Merdzavan', 'price' => '1400'],
    ['label' => 'Geghanist', 'price' => '1400'],
];

